server:
  port: 8001


spring:
  autoconfigure:
    #????? ????
    exclude: com.alibaba.druid.spring.boot.autoconfigure.DruidDataSourceAutoConfigure
  # dynamic-datasource-spring-boot-starter ??????????
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    dynamic:
      primary: master # ???????????????????? master
      datasource:
        master:
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://localhost:3306/kotlin
          username: root
          password: 888
        db2:
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://localhost:3306/kotlin2
          username: root
          password: 888
      #dynamic - ????
      druid:
        initialSize: 5
        minIdle: 5
        maxActive: 30
        maxWait: 60000
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: SELECT 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxPoolPreparedStatementPerConnectionSize: 20
        filters: stat,wall,slf4j,config
        useGlobalDataSourceStat: true
        stat:
          log-slow-sql: true
          merge-sql: true
          slow-sql-millis: 10000
    druid:
      # ????
      statViewServlet:
        enabled: true
        # ???????????????
        allow:
        url-pattern: /druid/*
        # ???????????
        login-username: root
        login-password: 888


